spring:
  application:
    name: HEAD-MANAGER
  datasource:
    url: jdbc:postgresql://localhost:5432/Management
    username: egor
    password: postgres
#  jpa:
#    properties:
#      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
