spring:
  application:
    name: HEAD-MANAGER
  datasource:
    url: jdbc:postgresql://localhost:5432/Management
    username: egor
    password: postgres

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
