spring:
  application:
    name: NOTIFICATOR
  datasource:
    url: jdbc:postgresql://localhost:5432/Notifications
    username: egor
    password: postgres
#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: test-client2
#            authorization-grant-type: authorization_code
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8180/realms/test-realm
#            user-name-attribute: preferred_username
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8180/realms/test-realm


server:
  port: 8083

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
