spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
#      auth 8081
#      head 8082
#      notificator 8083
#      kc 8180



#      routes:
#        - id: head-manager
#          uri: lb://HEAD-MANAGER
#          predicates:
#            - Path=/head-manager/**
#          filters:
#            - AuthenticationFilter
#
#        - id: notificator
#          uri: lb://NOTIFICATOR
#          predicates:
#            - Path=/notificator/**
#          filters:
#            - AuthenticationFilter
#
#        - id: authenticator
#          uri: lb://AUTHENTICATOR
#          predicates:
#            - Path=/auth/**

#        - id: user-manager
#          uri: lb://USER-MANAGER
#          predicates:
#            - Path=/auth/**
      discovery:
        locator:
          enabled: true
#          lower-case-service-id: true

jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP

server:
  port: 8765

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"