spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/ediary
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ui-client
            client-secret: NCFAsIyNDM2MxTS8IMDE7WGQ6wt2pXlV
            authorization-grant-type: authorization_code
            scope:
              - openid
              - microprofile-jwt



keycloak:
  realm: ediary
  domain: localhost:8180
  adminClientId: ui-client
  adminClientSecret: NCFAsIyNDM2MxTS8IMDE7WGQ6wt2pXlV
  urls:
    auth: http://${keycloak.domain}


server:
  port: 8081

app:
  base-url:
    notificator: http://localhost:8083
    head-manager: http://localhost:8082

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"